# Generated by Django 5.0.1 on 2024-02-18 06:16

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Course_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Course_name', models.CharField(default='(*_*)', max_length=50, unique=True)),
                ('Date_added', models.DateTimeField(auto_now=True)),
                ('No_of_enrolment', models.IntegerField(default=0)),
                ('Course_description', models.CharField(max_length=1200, null=True)),
                ('Image_link', models.CharField(default=user.models.def_img, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('Topic_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Topic_name', models.CharField(default='(*-*)', max_length=50)),
                ('Topic_description', models.CharField(max_length=1200, null=True)),
                ('Last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CTtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topics_IDs', models.CharField(max_length=10000, null=True)),
                ('Related_topic_IDs', models.CharField(max_length=10000, null=True)),
                ('Topic_Sources', models.CharField(max_length=1000, null=True)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_cid', to='user.courses')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.CharField(default=user.models.def_img, max_length=200)),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed_topic_IDs', models.CharField(max_length=1000, null=True)),
                ('Incompleted_topic_IDs', models.CharField(max_length=1000, null=True)),
                ('Start_date', models.DateTimeField(auto_now=True)),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_cid', to='user.courses')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_uid', to='user.profile')),
            ],
        ),
    ]
