# Generated by Django 5.0.1 on 2024-02-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cttable',
            name='Related_topic_IDs',
        ),
    ]
