# Generated by Django 5.0.1 on 2024-02-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_cttable_related_topic_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uname',
            new_name='uid',
        ),
    ]
